### PR TITLE
Judy Tuan made this suggestion: (quote) my friend richard made this b…

### PR DESCRIPTION
**Pull request by DianaVashti**
…usiness generator, please randomly add pull requests to it to make him go: wtf where are these people coming from. (endquote) Adds Rube Goldberg machines to types array.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Where the fuck did you even find this, @judytuna. :D hahahahahaha

**Comment by judytuna** [comment]
GR8 SUCCESS 

OMG YOUR BEARD?!?!

**Comment by RichardLitt** [comment]
Where did you even say this

**Comment by RichardLitt** [comment]
ahahahahahaah

**Comment by judytuna** [comment]
i "follow" you in github which means new public repos show up in my "feed," which i barely ever look at but i tripped over the repo name hahah

**Comment by RichardLitt** [comment]
That makes sense. :)

**Comment by judytuna** [comment]
i work at @learnersguild now!!! it's a 40-week, pay-when-you-get-a-job software apprenticeship for ppl from underrepresented groups/identities/backgrounds in tech. di's also on staff at the guild =D after going through the program herself! 

tell us all ur project ideas

**Comment by RichardLitt** [comment]
That sounds super cool! Oh man! 

Can I help? Looking over your GitHub profile, I wonder if what I've been doing at Maintainer might be able to be of interest. Alternatively, I've got project ideas. :) Got time for a video call at some point?

**Pull request merged**
